### ISSUE TITLE
Complete Discovery Workflow

### ISSUE THREAD

**Issue by barkerth** [barkerth/FirmwareUpdateServices#2]
Tasks to complete include:

- Deserialize accessory code validation response from UI client
- Pass accessory code validation response to attached clients, with (if encryption supported) service public key
- Client validate code and return device metadata
- Service stores device metadata, and informs UI that registration is complete for a list of attached devices.

**Comment by lmfedy** [comment]
I have been able to successfully integrate the first part of the discovery between the devices and the discovery service. If you change the address of your mock device to match a device you start (http://localhost:8081/device/enroll), it will return the enroll response as expected. And push the correct information to the mock UI.

**Comment by barkerth** [comment]
Hi All,

So, I've been beating my ahead against Java concurrency issues, trying to
finish off the discovery service.  I really think that once I get past this
one, the rest will essentially be similar.  *fingers crossed*

I'm trying to make regular commits, but I'm not pushing code that breaks
the build.  I expect that my next commit will be tonight.

Thomas

**Comment by barkerth** [comment]
Lauren, William,

I've completed the Discovery workflow.  All changes have been committed and
are ready for integration with other components.  I've also left some
samples of the expected JSON in comments on DiscoveryService.java.
Hopefully the mock endpoints that I've built for client devices and the UI
will be of some help when integrating with your pieces.

I expect that I will begin building the Firmware Update Retrieval workflow
tomorrow.  If either of you have any questions, you can reach me via
Hangouts (I've always got my phone on me) or via email.

Have a good weekend!
Thomas
