### ISSUE TITLE
Encryption Issue

### ISSUE THREAD

**Issue by lmfedy** [barkerth/FirmwareUpdateServices#3]
Tom,

There was an issue with the encryption services using RSA. I had to change the utility to block cipher any strings that were longer than 256 bytes. I have created a new branch in this repo called dev that does this in the utility (CryptoUtility Line 210). 

In the dev branch, the discovery service now also decrypts the response, if necessary, before creating the CodeValidationResponse object (DiscoveryService Line 283). I have been able to integrate 3 IoTDevice object with this service using both encrypted and non-encrypted type devices.

Thanks,
Lauren

**Comment by barkerth** [comment]
Sounds good.  I've merged your changes into Master.
Thanks!
